#! /bin/sh

xsetroot -cursor_name left_ptr &
compton&
redshift&
feh --bg-scale /home/troydm/.dotcentral/configurations/troymac/wallpaper/snow-leopard-bg.jpg

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config focus_follows_pointer true
bspc config border_width         4
bspc config active_border_color \#FFFFFF
bspc config focused_border_color \#FFFFFF
bspc config normal_border_color \#000000
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a mpv state=floating
