# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, ... }:

{
  imports =
    [ <nixpkgs/nixos/modules/installer/scan/not-detected.nix>
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "usb_storage" "usbhid" "sd_mod" ];
  boot.kernelModules = [ "kvm-intel" "wl" "8192eu" ];
  boot.blacklistedKernelModules = [ "rtl8xxxu" ];
  boot.extraModulePackages = [ config.boot.kernelPackages.broadcom_sta config.boot.kernelPackages.rtl8192eu ];
  boot.cleanTmpDir = true;
  boot.extraModprobeConfig = ''
    options snd-hda-intel index=0 model=intel-mac-auto id=PCH
    options snd-hda-intel index=1 model=intel-mac-auto id=HDMI
    options snd-hda-intel model=mbp101 position_fix=1
    options hid_apple fnmode=2
  '';

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/04c9fc1c-3b99-4a5f-b73a-313d575bdce9";
      fsType = "ext4";
      options = ["rw,relatime,discard,data=ordered"];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/67E3-17ED";
      fsType = "vfat";
    };

  swapDevices = [ ];

  hardware.pulseaudio.enable = true;
  hardware.opengl.extraPackages = [ pkgs.vaapiIntel ];

  nix.maxJobs = lib.mkDefault 4;
  powerManagement = {
    enable = true;
    cpuFreqGovernor = "powersave";
  };
}
